// Code generated by protoc-gen-go. DO NOT EDIT.
// source: answer.proto

package models

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Event struct {
	Count                int32    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Timestamp            int32    `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6f97dbee99679ee, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Event) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Event) GetTimestamp() int32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type Request struct {
	From                 int32    `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   int32    `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6f97dbee99679ee, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetFrom() int32 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *Request) GetTo() int32 {
	if m != nil {
		return m.To
	}
	return 0
}

func (m *Request) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type Answer struct {
	Count                int32    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Answer) Reset()         { *m = Answer{} }
func (m *Answer) String() string { return proto.CompactTextString(m) }
func (*Answer) ProtoMessage()    {}
func (*Answer) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6f97dbee99679ee, []int{2}
}

func (m *Answer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Answer.Unmarshal(m, b)
}
func (m *Answer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Answer.Marshal(b, m, deterministic)
}
func (m *Answer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Answer.Merge(m, src)
}
func (m *Answer) XXX_Size() int {
	return xxx_messageInfo_Answer.Size(m)
}
func (m *Answer) XXX_DiscardUnknown() {
	xxx_messageInfo_Answer.DiscardUnknown(m)
}

var xxx_messageInfo_Answer proto.InternalMessageInfo

func (m *Answer) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Answer) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6f97dbee99679ee, []int{3}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Event)(nil), "models.Event")
	proto.RegisterType((*Request)(nil), "models.Request")
	proto.RegisterType((*Answer)(nil), "models.Answer")
	proto.RegisterType((*Empty)(nil), "models.Empty")
}

func init() { proto.RegisterFile("answer.proto", fileDescriptor_c6f97dbee99679ee) }

var fileDescriptor_c6f97dbee99679ee = []byte{
	// 286 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x50, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0x26, 0xa9, 0x49, 0xc8, 0x58, 0x5b, 0x58, 0x44, 0x42, 0xec, 0xa1, 0xec, 0xa9, 0x78, 0xd8,
	0x40, 0xbd, 0x09, 0x1e, 0x8a, 0x14, 0xbc, 0x09, 0x79, 0x83, 0xad, 0x9d, 0x96, 0x40, 0xb3, 0x1b,
	0xb3, 0x13, 0xa5, 0x57, 0xdf, 0x40, 0x7c, 0x34, 0x5f, 0xc1, 0x07, 0x11, 0x67, 0x13, 0x7b, 0xf5,
	0x36, 0x3f, 0xdf, 0x7c, 0xdf, 0x7c, 0x1f, 0x8c, 0xb5, 0x71, 0x6f, 0xd8, 0xaa, 0xa6, 0xb5, 0x64,
	0x45, 0x5c, 0xdb, 0x2d, 0x1e, 0x5c, 0x3e, 0xdb, 0x5b, 0xbb, 0x3f, 0x60, 0xa1, 0x9b, 0xaa, 0xd0,
	0xc6, 0x58, 0xd2, 0x54, 0x59, 0xe3, 0x3c, 0x2a, 0xbf, 0xee, 0xb7, 0xdc, 0x6d, 0xba, 0x5d, 0x81,
	0x75, 0x43, 0x47, 0xbf, 0x94, 0x4f, 0x10, 0xad, 0x5f, 0xd1, 0x90, 0xb8, 0x84, 0xe8, 0xd9, 0x76,
	0x86, 0xb2, 0x60, 0x1e, 0x2c, 0xa2, 0xd2, 0x37, 0x42, 0xc0, 0x19, 0x1d, 0x1b, 0xcc, 0xc2, 0x79,
	0xb0, 0x48, 0x4b, 0xae, 0xc5, 0x0c, 0x52, 0xaa, 0x6a, 0x74, 0xa4, 0xeb, 0x26, 0x1b, 0x31, 0xfa,
	0x34, 0x90, 0x2b, 0x48, 0x4a, 0x7c, 0xe9, 0xd0, 0xf1, 0xf1, 0xae, 0xb5, 0x75, 0xcf, 0xc8, 0xb5,
	0x98, 0x40, 0x48, 0x96, 0xe9, 0xa2, 0x32, 0x24, 0xfb, 0x27, 0x30, 0x3a, 0x09, 0xc8, 0x25, 0xc4,
	0x2b, 0xb6, 0xf9, 0xff, 0xa7, 0x64, 0x02, 0xd1, 0xfa, 0xd7, 0xd6, 0xf2, 0x23, 0x80, 0x98, 0x1d,
	0x39, 0x71, 0x0f, 0x69, 0x89, 0x7a, 0xeb, 0xfd, 0x4d, 0x95, 0x0f, 0x4b, 0xf5, 0xdf, 0xe5, 0x93,
	0x61, 0xe0, 0xb5, 0xe4, 0xf4, 0xfd, 0xeb, 0xfb, 0x33, 0x4c, 0x45, 0x52, 0xa0, 0x3f, 0x7f, 0x84,
	0xf3, 0x87, 0x16, 0x35, 0xa1, 0x27, 0xb8, 0x18, 0xf0, 0xdc, 0xe6, 0x57, 0xca, 0xc7, 0xaa, 0x86,
	0x58, 0x15, 0xeb, 0x4b, 0xc1, 0x34, 0x63, 0x39, 0xd0, 0xdc, 0x05, 0x37, 0x9b, 0x98, 0x31, 0xb7,
	0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x95, 0x94, 0x0c, 0x65, 0xbe, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EventsClient is the client API for Events service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EventsClient interface {
	ReadEvent(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Answer, error)
	CreateEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*empty.Empty, error)
}

type eventsClient struct {
	cc *grpc.ClientConn
}

func NewEventsClient(cc *grpc.ClientConn) EventsClient {
	return &eventsClient{cc}
}

func (c *eventsClient) ReadEvent(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Answer, error) {
	out := new(Answer)
	err := c.cc.Invoke(ctx, "/models.Events/ReadEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsClient) CreateEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/models.Events/CreateEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventsServer is the server API for Events service.
type EventsServer interface {
	ReadEvent(context.Context, *Request) (*Answer, error)
	CreateEvent(context.Context, *Event) (*empty.Empty, error)
}

// UnimplementedEventsServer can be embedded to have forward compatible implementations.
type UnimplementedEventsServer struct {
}

func (*UnimplementedEventsServer) ReadEvent(ctx context.Context, req *Request) (*Answer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadEvent not implemented")
}
func (*UnimplementedEventsServer) CreateEvent(ctx context.Context, req *Event) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEvent not implemented")
}

func RegisterEventsServer(s *grpc.Server, srv EventsServer) {
	s.RegisterService(&_Events_serviceDesc, srv)
}

func _Events_ReadEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServer).ReadEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.Events/ReadEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServer).ReadEvent(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Events_CreateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServer).CreateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.Events/CreateEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServer).CreateEvent(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

var _Events_serviceDesc = grpc.ServiceDesc{
	ServiceName: "models.Events",
	HandlerType: (*EventsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadEvent",
			Handler:    _Events_ReadEvent_Handler,
		},
		{
			MethodName: "CreateEvent",
			Handler:    _Events_CreateEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "answer.proto",
}
