// Code generated by protoc-gen-go. DO NOT EDIT.
// source: answ.proto

package buffers

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AnswerStruct struct {
	Count                int64    `protobuf:"varint,1,opt,name=Count,json=count,proto3" json:"Count,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=Type,json=type,proto3" json:"Type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnswerStruct) Reset()         { *m = AnswerStruct{} }
func (m *AnswerStruct) String() string { return proto.CompactTextString(m) }
func (*AnswerStruct) ProtoMessage()    {}
func (*AnswerStruct) Descriptor() ([]byte, []int) {
	return fileDescriptor_aeaaf2a2464ca163, []int{0}
}

func (m *AnswerStruct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnswerStruct.Unmarshal(m, b)
}
func (m *AnswerStruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnswerStruct.Marshal(b, m, deterministic)
}
func (m *AnswerStruct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnswerStruct.Merge(m, src)
}
func (m *AnswerStruct) XXX_Size() int {
	return xxx_messageInfo_AnswerStruct.Size(m)
}
func (m *AnswerStruct) XXX_DiscardUnknown() {
	xxx_messageInfo_AnswerStruct.DiscardUnknown(m)
}

var xxx_messageInfo_AnswerStruct proto.InternalMessageInfo

func (m *AnswerStruct) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *AnswerStruct) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func init() {
	proto.RegisterType((*AnswerStruct)(nil), "buffers.AnswerStruct")
}

func init() { proto.RegisterFile("answ.proto", fileDescriptor_aeaaf2a2464ca163) }

var fileDescriptor_aeaaf2a2464ca163 = []byte{
	// 106 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0xcc, 0x2b, 0x2e,
	0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4f, 0x2a, 0x4d, 0x4b, 0x4b, 0x2d, 0x2a, 0x56,
	0xb2, 0xe0, 0xe2, 0x71, 0xcc, 0x2b, 0x2e, 0x4f, 0x2d, 0x0a, 0x2e, 0x29, 0x2a, 0x4d, 0x2e, 0x11,
	0x12, 0xe1, 0x62, 0x75, 0xce, 0x2f, 0xcd, 0x2b, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0e, 0x62,
	0x4d, 0x06, 0x71, 0x84, 0x84, 0xb8, 0x58, 0x42, 0x2a, 0x0b, 0x52, 0x25, 0x98, 0x14, 0x18, 0x35,
	0x38, 0x83, 0x58, 0x4a, 0x2a, 0x0b, 0x52, 0x93, 0xd8, 0xc0, 0x26, 0x19, 0x03, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x5a, 0xa4, 0xff, 0x77, 0x57, 0x00, 0x00, 0x00,
}
